### ISSUE TITLE
smallvis_rep() not working

### ISSUE THREAD

**Issue by milanhej** [jlmelville/smallvis#1]
Very useful and fun package.  But trying to run the sample code, I get an error messge.

library(smallvis)
tsne_iris_best <- smallvis_rep(nrep = 10, iris, perplexity = 25, ret_extra = TRUE)

>23:16:10 Starting embedding # 1 of 10
>Error in make_smallvis_cb(X) : argument "X" is missing, with no default

Thanks!

**Comment by jlmelville** [comment]
Thanks for the kind words about the package. There's a mistake in the `README.md`,  bind the dataframe (in this case, `iris`) to the `X` argument explicitly, i.e.:
```R
tsne_iris_best <- smallvis_rep(nrep = 10, X = iris, perplexity = 25, ret_extra = TRUE)
```
I will fix `README.md`. Thanks for bringing that to my attention.

**Comment by milanhej** [comment]
Thanks!  All works well now.
