### ISSUE TITLE
Error in if (Z == 0) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by cgpu** [jlmelville/smallvis#2]
Thank you for such an extensive package and for including examples for each and every function. The example with iris runs no problem; I try to reproduce for diff dataset of similar `str()` but I get the following error:

# Load dataset, inspect `str`
i:
``` r
URL  <- "http://bit.ly/data_shannon_error"
goblins_df <- read.csv(URL) 
utils::str(goblins_df)
```
o:
```
'data.frame':	373 obs. of  9 variables:
 $ bone_length  : num  0.355 0.324 0.63 0.472 0.469 ...
 $ rotting_flesh: num  0.351 0.431 0.581 0.494 0.517 ...
 $ hair_length  : num  0.466 0.205 0.647 0.557 0.621 ...
 $ has_soul     : num  0.781 0.258 0.505 0.564 0.625 ...
 $ red          : int  255 255 255 255 255 255 255 255 255 255 ...
 $ green        : int  255 255 255 255 255 255 255 255 255 255 ...
 $ blue         : int  255 255 255 255 255 255 255 255 255 255 ...
 $ alpha        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ type         : Factor w/ 3 levels "Ghost","Ghoul",..: 2 1 2 2 3 2 2 2 3 3 ...
```

#  `smallvis()` call
i:
``` r
tsne <- smallvis(data, 
                          perplexity = 30, 
                          verbose    = TRUE)
```
# Error:
o: 
```
Error in if (Z == 0) { : missing value where TRUE/FALSE needed
6.shannon(Di, beta[i])
5.x2aff(X, perplexity, tol = 1e-05, kernel = kernel, verbose = verbose)
4.sne_init(cost, X, perplexity = perplexity, kernel = inp_kernel, symmetrize = "symmetric", normalize = TRUE, verbose = verbose, ret_extra = ret_extra)
3.cost$init(cost, X, verbose = verbose, ret_extra = ret_extra, max_iter = max_iter)
2.cost_init(cost_fn, X, max_iter = max_iter, verbose = verbose, ret_extra = ret_optionals)
1.smallvis(data, perplexity = 30, verbose = TRUE)
```

Does it have sth to do with `shannon`()? I ctrl + F in your code and source code from `pgirmess ::shannon()` but can't seem to detect where this error is exported from.

**Comment by jlmelville** [comment]
Hello, thanks for the report. The error is due to `goblins_df[372:373, ]` containing some `NA` entries. By excluding those problematic observations, the following should work:

```R
tsne <- smallvis(goblins_df[1:371, ], 
                  perplexity = 30, 
                  verbose    = TRUE)
```

The fix for this is to  add a check for `NA` on input and `stop`  in that case.

**Comment by cgpu** [comment]
It works, thanks for catching this EDA bit.  
I forgot to remove those from saved dataset. 
![](https://raw.githubusercontent.com/cgpu/kaggle_goblins_data/master/plot_missingness.png)

**Comment by jlmelville** [comment]
Glad it's working for you now. I have checked in the change so that the error message should be better in the future.
