### ISSUE TITLE
A reference for scaled PCA initialisation

### ISSUE THREAD

**Issue by dkobak** [jlmelville/smallvis#3]
Hey, do you by any chance know of any reference for the scaled PCA initialization? Perhaps there is some paper that at least mentions PCA initialization as a possibility and explicitly says that one needs to use scaled PCA in this case? I am not able to find any reference at all.

I looked here https://jlmelville.github.io/smallvis/init.html and here http://jlmelville.github.io/sneer/references.html but did not find anything. In fact, in your References list you cite our preprint in the Initialization setting, but I think I borrowed the scaled PCA idea from your pages :-) I am preparing a revision right now and it'd be good to have some reference for this...

**Comment by jlmelville** [comment]
I think I came up with the scaled PCA idea on my own. The JSE paper uses PCA as initialization so that was the direct inspiration, although any requirement for scaling isn't mentioned.

**Comment by dkobak** [comment]
Thanks. I guess I will add a citation directly to https://jlmelville.github.io/smallvis/init.html then.

**Comment by dkobak** [comment]
(This is what I did in the end, so I'm closing it ;-)
