### ISSUE TITLE
Unable to install smallvis  

### ISSUE THREAD

**Issue by SameOldSamOld** [jlmelville/smallvis#4]
Hi there, I followed your readme and installed RSpectra and vizier successfully, but could not install smallvis. Hopefully there is something small I missed!

Thank you.

```
> library(RSpectra)
> library(vizier)
> devtools::install_github("jlmelville/smallvis/smallvis")
Downloading GitHub repo jlmelville/smallvis@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/jlmelville/smallvis/tarball/HEAD' failed
> R.version.string
[1] "R version 4.2.1 (2022-06-23)"
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] devtools_2.4.5        usethis_2.1.6         vizier_0.4.2          RSpectra_0.16-1       data.table_1.14.6     ComplexHeatmap_2.12.1
 [7] BiocParallel_1.30.4   forcats_0.5.2         stringr_1.4.1         dplyr_1.0.10          purrr_0.3.5           readr_2.1.3          
[13] tidyr_1.2.1           tibble_3.1.8          ggplot2_3.4.0         tidyverse_1.3.2       SeuratObject_4.1.3    Seurat_4.3.0         
[19] SCopeLoomR_0.13.0     SCENIC_1.3.1          AUCell_1.18.1         flowCore_2.8.0       
```

**Comment by jlmelville** [comment]
That's very strange. I just tried installing (admittedly not on a Mac) and it worked. All we have to go on is:

```
download from 'https://api.github.com/repos/jlmelville/smallvis/tarball/HEAD' failed
```

The only suggestion I can make is to see if it was an intermittent failure and re-run `devtools::install_github("jlmelville/smallvis/smallvis")`. If you already tried that then see if a different package can be installed from github (probably not one you are current using is a good idea), e.g. try ` devtools::install_github("r-lib/revdepcheck")`. If that also doesn't work then you have a problem with installing from github.

**Comment by SameOldSamOld** [comment]
Hmm, revdepcheck and vizier successfully installed from github. I am not sure why it has failed. I will let you know if I figure out a way to get it installed.

**Comment by jlmelville** [comment]
This shouldn't make a difference but you could try `devtools::install_github("jlmelville/smallvis", subdir = "smallvis")`

**Comment by SameOldSamOld** [comment]
Wow, that worked!
Thank you, I have no idea why though! But I'm happy with it :)

**Comment by jlmelville** [comment]
@SameOldSamOld I don't know why either, but I am glad it worked. Thank you for letting me know about the problem, I have updated the `README` to use the `subdir` argument in case there has been a change to either `devtools` or github that I didn't know about.
